### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by weikecloud** [Chanzhaoyu/luma-mock#1]
SvelteKitError: Not found: /dev-sw.js

**Comment by weikecloud** [comment]
SvelteKitError: Not found: /@vite-plugin-pwa/pwa-entry-point-loaded

**Comment by Chanzhaoyu** [comment]
> SvelteKitError: Not found: /@vite-plugin-pwa/pwa-entry-point-loadedSvelteKitError：未找到：/@vite-plugin-pwa/pwa-entry-point-loaded

Node 是什么版本，最好有控制台截图

**Comment by weikecloud** [comment]
node版本20
![image](https://github.com/Chanzhaoyu/luma-mock/assets/36788191/71018799-80cc-483f-ab51-c91c172ae1f8)

**Comment by Chanzhaoyu** [comment]
> node版本20 ![image](https://private-user-images.githubusercontent.com/36788191/341297710-71018799-80cc-483f-ab51-c91c172ae1f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NjU2NTcsIm5iZiI6MTcxODg2NTM1NywicGF0aCI6Ii8zNjc4ODE5MS8zNDEyOTc3MTAtNzEwMTg3OTktODBjYy00ODNmLWFiNTEtYzkxYzE3MmFlMWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA2MzU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMjkyMjk5ZmY5NmQyZjZkMmQzZDFlYzliNmY4ZDAzNmUwYzY0NzIzYzM0MGMwOGNjNzE2Nzc4NjhiZWVmMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.axm8beEPR8YpyEnz11CfSrxBOjX-ZVrSbTcytY2Oku4)

我本地没有复现这个情况，今天代码改动较大，要不尝试删除项目重新 `git clone` 然后重装依赖试试？

**Comment by weikecloud** [comment]
![image](https://github.com/Chanzhaoyu/luma-mock/assets/36788191/476d9d19-9c84-45fa-84fd-44ce6553a2af)
![image](https://github.com/Chanzhaoyu/luma-mock/assets/36788191/92e55e95-9fa9-4eec-8f74-2032b3500f8b)
已拉取最新版，好像还是这样

**Comment by Chanzhaoyu** [comment]
> ![image](https://private-user-images.githubusercontent.com/36788191/341299008-476d9d19-9c84-45fa-84fd-44ce6553a2af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NjYyMjIsIm5iZiI6MTcxODg2NTkyMiwicGF0aCI6Ii8zNjc4ODE5MS8zNDEyOTkwMDgtNDc2ZDlkMTktOWM4NC00NWZhLTg0ZmQtNDRjZTY1NTNhMmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA2NDUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkM2IyZGFjOTE1NmQ4ZTVkNWM2ZDA5ZmM0MDk4MzY2NmU0MWZiZDJlMzEzZDk2NjZkZTQ0N2U3MTA4MjNmM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zAS7uy12W1LOjvJ3c52tNzkG91FIfX0vZUh2C3xAO3U) ![image](https://private-user-images.githubusercontent.com/36788191/341299273-92e55e95-9fa9-4eec-8f74-2032b3500f8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NjYyMjIsIm5iZiI6MTcxODg2NTkyMiwicGF0aCI6Ii8zNjc4ODE5MS8zNDEyOTkyNzMtOTJlNTVlOTUtOWZhOS00ZWVjLThmNzQtMjAzMmIzNTAwZjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA2NDUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2NGVkMjcyYWE1ZDM1MzFiNTIyNzIyY2ZlNzVmMzkyZWE5N2ExZjA0YTBiYTM4YTMxODVmNTM4Y2I5MzNkZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RJ_VeP0ar9OgxP2x-bY2VcCDauze2rdbn6coxYlDhQ8) 已拉取最新版，好像还是这样

你的具体 node 版本是多少，我创建个环境测试下

**Comment by weikecloud** [comment]
我发现第一次没有运行build的时候，就会出现找不到文件
![image](https://github.com/Chanzhaoyu/luma-mock/assets/36788191/97e1472d-24d1-4edf-b2cf-640bd96d4915)
然后我试了一下运行build和preview 就没问题了

**Comment by weikecloud** [comment]
> > ![image](https://private-user-images.githubusercontent.com/36788191/341299008-476d9d19-9c84-45fa-84fd-44ce6553a2af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NjYyMjIsIm5iZiI6MTcxODg2NTkyMiwicGF0aCI6Ii8zNjc4ODE5MS8zNDEyOTkwMDgtNDc2ZDlkMTktOWM4NC00NWZhLTg0ZmQtNDRjZTY1NTNhMmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA2NDUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkM2IyZGFjOTE1NmQ4ZTVkNWM2ZDA5ZmM0MDk4MzY2NmU0MWZiZDJlMzEzZDk2NjZkZTQ0N2U3MTA4MjNmM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zAS7uy12W1LOjvJ3c52tNzkG91FIfX0vZUh2C3xAO3U) ![image](https://private-user-images.githubusercontent.com/36788191/341299273-92e55e95-9fa9-4eec-8f74-2032b3500f8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NjYyMjIsIm5iZiI6MTcxODg2NTkyMiwicGF0aCI6Ii8zNjc4ODE5MS8zNDEyOTkyNzMtOTJlNTVlOTUtOWZhOS00ZWVjLThmNzQtMjAzMmIzNTAwZjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA2NDUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2NGVkMjcyYWE1ZDM1MzFiNTIyNzIyY2ZlNzVmMzkyZWE5N2ExZjA0YTBiYTM4YTMxODVmNTM4Y2I5MzNkZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RJ_VeP0ar9OgxP2x-bY2VcCDauze2rdbn6coxYlDhQ8) 已拉取最新版，好像还是这样
> 
> 你的具体 node 版本是多少，我创建个环境测试下

node版本 v20.10.0

**Comment by weikecloud** [comment]
dev 有问题， preview 没问题，不知道为什么

**Comment by weikecloud** [comment]
![image](https://github.com/Chanzhaoyu/luma-mock/assets/36788191/3ac2e6c9-c21a-439b-b4a2-d4e10e3239f3)
![image](https://github.com/Chanzhaoyu/luma-mock/assets/36788191/916d5100-32ec-4b8c-9794-1db256e0f8f7)
我访问官方是能正常访问的

**Comment by Chanzhaoyu** [comment]
> dev 有问题， preview 没问题，不知道为什么

应该知道问题了，是第一次运行的触发的类型错误，可以运行 `pnpm prepare` 消除。

**Comment by weikecloud** [comment]
我运行了pnpm prepare，再运行pnpm dev，还是一样的报错哦

**Comment by Chanzhaoyu** [comment]
> 我运行了pnpm prepare，再运行pnpm dev，还是一样的报错哦

啊，奇了怪了。

**Comment by weikecloud** [comment]
我pnpm版本是9.4.0 这个没有影响吧？

**Comment by weikecloud** [comment]
我好像知道什么问题了，可能是我的浏览器里面有5173这个端口的缓存，导致访问http://localhost:5173 的时候会自动请求某些文件，没有这些文件的时候，会出错，导致不显示，我用无痕迹浏览器试了一下，没问题了！

**Comment by Chanzhaoyu** [comment]
> 我好像知道什么问题了，可能是我的浏览器里面有5173这个端口的缓存，导致访问http://localhost:5173 的时候会自动请求某些文件，没有这些文件的时候，会出错，导致不显示，我用无痕迹浏览器试了一下，没问题了！

本地开发建议勾选这一项

<img width="803" alt="image" src="https://github.com/Chanzhaoyu/luma-mock/assets/24789441/4ec086f2-6336-480e-8b78-f73be12927f7">
